---
stages:
  - name: package-dev1
    inputs:
      - type: git
        branch: dev1
    triggers:
      - type: commit
    properties:
      - name: SAUCE_USERNAME
        value: moberlin
        type: text
      - name: SAUCE_ACCESS_KEY
        value: 6dd2c2e8-66e8-4b20-9abc-14a05f17ca41
        type: text
    jobs:
      - name: distribution
        type: builder
        artifact_dir: build
        build_type: npm
        enable_tests: false
