---
stages:
  - name: package-dev1
    inputs:
      - type: git
        branch: dev1
    triggers:
      - type: commit
    properties:
      - name: SAUCE_USERNAME
        value: ${SAUCE_USER}
        type: text
      - name: SAUCE_ACCESS_KEY
        value: ${SAUCE_KEY}
        type: text
    jobs:
      - name: distribution
        type: builder
        artifact_dir: build
        build_type: npm
        enable_tests: false
